### ISSUE TITLE
Como conseguir acurácia de 100% no concurso no titanic?

### ISSUE THREAD

**Issue by NovaisGabriel** [NovaisGabriel/Kaggle_Codes#2]
Estou tentando obter uma acurácia de 100% na competição do kaggle. Vi que era possível, pois tinham competidores que tiveram essa nota. Alguma idéia?

**Comment by Franklin-oliveira** [comment]
Você já tentou uma regressão logística? 

É sempre bom, em qualquer projeto de data science, começar com um modelo baseline priorizando a alta explicabilidade. Então, a partir daí, você pode ir testando algoritmos mais complexos e estimando sua melhoria em termos de acurácia... 

Mas é difícil atingir 100% de acurácia fora da amostra. É bom tomar cuidado com overfitting...
